---
nport_acquisition_user: nport
nport_acquisition_group: nport
nport_acquisition_install_dir: /opt/nport-acquisition
nport_acquisition_config_dir: /etc/nport-acquisition
nport_acquisition_binary: "{{ nport_acquisition_install_dir }}/nport-agent"
nport_acquisition_binary_src: ""
nport_acquisition_config_file: "{{ nport_acquisition_config_dir }}/config.yml"
nport_acquisition_config_src: ""
nport_acquisition_textfile_dir: /var/lib/node_exporter/textfile_collector
nport_acquisition_service_name: nport-acquisition
nport_acquisition_env: {}
