site: example

agent:
  mode: passive-listening
  sub_mode: store
  store_timeout_seconds: 30
  test_duration_seconds: 60
  test_only_valid_crc: false

nports:
  - name: port_1
    host: 192.0.2.10
    port: 4001
    device_type: generic
    idle_gap_ms: 50
    serial:
      baud: 19200
      data_bits: 8
      parity: even
      stop_bits: 1
    detected_slaves:
      - 1
    slaves:
      - name: device_1
        address: 1
        registers:
          - register: 0
            register_name: value0
            register_type: int16

storage:
  local:
    - name: local-influx
      db-type: influxdb2
      db-url-env: INFLUX_HOST_LOCAL
      db-token-env: INFLUX_TOKEN_LOCAL
      db-org-env: INFLUX_ORG_LOCAL
      db-bucket-env: INFLUX_BUCKET_LOCAL
      db-measurement: example-nport
  remotes:
    - name: remote-influx
      db-type: influxdb2
      db-url-env: INFLUX_HOST_REMOTE
      db-token-env: INFLUX_TOKEN_REMOTE
      db-org-env: INFLUX_ORG_REMOTE
      db-bucket-env: INFLUX_BUCKET_REMOTE
      db-measurement: example-nport
